
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  pre_build:
    commands:
      - echo preBuild
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo postBuild

artifacts:
  files:
    - challenge-0.0.1-SNAPSHOT.jar
  base-directory: target
